# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2

  
defaults: &defaults
  docker:
    - image: maxsam4/solidity-kit

jobs:
  test-code:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Truffle Test
          command: truffle test
  test-code-coverage:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: NPM Install
          command: npm install
      - run:
          name: Get Permission
          command: chmod +x ./scripts/coverage.sh
      - run:
          name: Coverage Test
          command: ./scripts/coverage.sh
      - codecov/upload:
          file: {{ ./coverage/lcov.info }}


workflows:
  version: 2.1
  code_quality:
    jobs:
      - test-code
      - test-code-coverage
